/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;


import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alperen
 */
public class Albümler extends javax.swing.JFrame {

    /**
     * Creates new form Albümler
     */
    public Albümler() {
        initComponents();
        güncelle();
    }
    
    public void güncelle(){
        int i,j;
        
        try {
            Veritabanı.pstmt= Veritabanı.con.prepareStatement("SELECT * FROM albumler");
            Veritabanı.rs= Veritabanı.pstmt.executeQuery();
            ResultSetMetaData AlbumData = Veritabanı.rs.getMetaData();
            i = AlbumData.getColumnCount();
            DefaultTableModel RecordTable = (DefaultTableModel)albumTablo.getModel();
            RecordTable.setRowCount(0);
            while(Veritabanı.rs.next()){
            Vector columnData = new Vector();
            for(j=1;j<=i;j++){
             columnData.add(Veritabanı.rs.getString("album_id"));
             columnData.add(Veritabanı.rs.getString("album_ad"));
             columnData.add(Veritabanı.rs.getString("album_tarih"));
             columnData.add(Veritabanı.rs.getString("album_tur"));
            }
            RecordTable.addRow(columnData);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Albümler.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        albumTablo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtf_ad = new javax.swing.JTextField();
        txtf_tarih = new javax.swing.JTextField();
        txtf_tür = new javax.swing.JTextField();
        ekleButon = new javax.swing.JButton();
        silButon = new javax.swing.JButton();
        güncelleButon = new javax.swing.JButton();
        bitirButon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        albumTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Adı", "Çıkış Tarihi", "Türü"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        albumTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                albumTabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(albumTablo);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Albüm Adı");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Çıkış Tarihi");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Türü");

        ekleButon.setText("EKLE");
        ekleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleButonActionPerformed(evt);
            }
        });

        silButon.setText("SİL");
        silButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silButonActionPerformed(evt);
            }
        });

        güncelleButon.setText("GÜNCELLE");
        güncelleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                güncelleButonActionPerformed(evt);
            }
        });

        bitirButon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bitirButon.setText("BİTİR");
        bitirButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bitirButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(ekleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtf_tarih)
                                        .addComponent(txtf_tür, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(silButon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                        .addComponent(güncelleButon)))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtf_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bitirButon, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtf_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtf_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtf_tür, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ekleButon)
                            .addComponent(silButon)
                            .addComponent(güncelleButon))
                        .addGap(72, 72, 72)
                        .addComponent(bitirButon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(289, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ekleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleButonActionPerformed
        
        try {
            Veritabanı.pstmt= Veritabanı.con.prepareStatement("INSERT INTO albumler(album_ad,album_tarih,album_tur) values (?,?,?)");
            Veritabanı.pstmt.setString(1, txtf_ad.getText());
            Veritabanı.pstmt.setString(2, txtf_tarih.getText());
            Veritabanı.pstmt.setString(3, txtf_tür.getText());
            Veritabanı.pstmt.executeUpdate();
            güncelle();
            
        } catch (SQLException ex) {
            Logger.getLogger(Albümler.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_ekleButonActionPerformed

    private void albumTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_albumTabloMouseClicked
        
        DefaultTableModel RecordTable = (DefaultTableModel) albumTablo.getModel();
        int seçilen = albumTablo.getSelectedRow();
        txtf_ad.setText(RecordTable.getValueAt(seçilen, 1).toString());
        txtf_tarih.setText(RecordTable.getValueAt(seçilen, 2).toString());
        txtf_tür.setText(RecordTable.getValueAt(seçilen, 3).toString());
        
        
        
        
    }//GEN-LAST:event_albumTabloMouseClicked

    private void silButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silButonActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel) albumTablo.getModel();
        int seçilen = albumTablo.getSelectedRow();
        try {
        int id = Integer.parseInt(RecordTable.getValueAt(seçilen, 0).toString());
        int veriyiSil = JOptionPane.showConfirmDialog(null,"Silmek istediğinizden emin misiniz?","Uyarı",JOptionPane.YES_NO_OPTION);
        if(veriyiSil== JOptionPane.YES_OPTION){
           
                Veritabanı.pstmt = Veritabanı.con.prepareStatement("DELETE FROM albumler WHERE album_id=?");
                Veritabanı.pstmt.setInt(1, id);
                Veritabanı.pstmt.executeUpdate();
                güncelle();
                txtf_ad.setText("");
                txtf_tarih.setText("");
                txtf_tür.setText("");
            } 
        }catch (SQLException ex) {
                Logger.getLogger(Albümler.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_silButonActionPerformed

    private void güncelleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_güncelleButonActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel) albumTablo.getModel();
        int seçilen = albumTablo.getSelectedRow();
        
         try {
            int id = Integer.parseInt(RecordTable.getValueAt(seçilen, 0).toString());
            Veritabanı.pstmt= Veritabanı.con.prepareStatement("UPDATE albumler set album_ad=?,album_tarih=?,album_tur=? WHERE album_id=?");
            Veritabanı.pstmt.setString(1, txtf_ad.getText());
            Veritabanı.pstmt.setString(2, txtf_tarih.getText());
            Veritabanı.pstmt.setString(3, txtf_tür.getText());
            Veritabanı.pstmt.setInt(4, id);
            Veritabanı.pstmt.executeUpdate();
            güncelle();
            
        } catch (SQLException ex) {
            Logger.getLogger(Albümler.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_güncelleButonActionPerformed

    private void bitirButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bitirButonActionPerformed
        Proje3.AdminPanel= new AdminPanel();
        Proje3.AdminPanel.setLocationRelativeTo(null);
        Proje3.AdminPanel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bitirButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Albümler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Albümler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Albümler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Albümler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Albümler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable albumTablo;
    private javax.swing.JButton bitirButon;
    private javax.swing.JButton ekleButon;
    private javax.swing.JButton güncelleButon;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton silButon;
    private javax.swing.JTextField txtf_ad;
    private javax.swing.JTextField txtf_tarih;
    private javax.swing.JTextField txtf_tür;
    // End of variables declaration//GEN-END:variables
}
