/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author Alperen
 */
public class KullanıcıPanel extends javax.swing.JFrame {

    /**
     * Creates new form KullanıcıPanel
     */
    public KullanıcıPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top10Buton = new javax.swing.JButton();
        şarkıButon = new javax.swing.JButton();
        sanatçıButon = new javax.swing.JButton();
        albümButon = new javax.swing.JButton();
        kullanıcıButon = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        profilButon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        top10Buton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        top10Buton.setText("TOP 10 LİSTELERİ");
        top10Buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                top10ButonActionPerformed(evt);
            }
        });

        şarkıButon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        şarkıButon.setText("ŞARKILAR");
        şarkıButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                şarkıButonActionPerformed(evt);
            }
        });

        sanatçıButon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sanatçıButon.setText("SANATÇILAR");
        sanatçıButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanatçıButonActionPerformed(evt);
            }
        });

        albümButon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        albümButon.setText("ALBÜMLER");
        albümButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albümButonActionPerformed(evt);
            }
        });

        kullanıcıButon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kullanıcıButon.setText("KULLANICILAR");
        kullanıcıButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanıcıButonActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Oturumu Kapat");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        profilButon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        profilButon.setText("Profil");
        profilButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(top10Buton)
                .addGap(42, 42, 42)
                .addComponent(şarkıButon, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(sanatçıButon, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profilButon, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(albümButon, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kullanıcıButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profilButon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(200, 200, 200)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(top10Buton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(şarkıButon, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sanatçıButon, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(albümButon, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullanıcıButon, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(342, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       Proje3.Giriş_seçimi = new Giriş_seçimi();
       Proje3.Giriş_seçimi.setLocationRelativeTo(null);
       Proje3.Giriş_seçimi.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void top10ButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_top10ButonActionPerformed
       Proje3.KullanıcıTop10= new KullanıcıTop10();
       Proje3.KullanıcıTop10.setLocationRelativeTo(null);
       Proje3.KullanıcıTop10.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_top10ButonActionPerformed

    private void sanatçıButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanatçıButonActionPerformed
        Proje3.KullanıcıSanatçı = new KullanıcıSanatçı();
        Proje3.KullanıcıSanatçı.setLocationRelativeTo(null);
        Proje3.KullanıcıSanatçı.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sanatçıButonActionPerformed

    private void albümButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albümButonActionPerformed
        Proje3.KullanıcıAlbüm= new KullanıcıAlbüm();
        Proje3.KullanıcıAlbüm.setLocationRelativeTo(null);
        Proje3.KullanıcıAlbüm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_albümButonActionPerformed

    private void şarkıButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_şarkıButonActionPerformed
        Proje3.KullanıcıŞarkı = new KullanıcıŞarkı();
        Proje3.KullanıcıŞarkı.setLocationRelativeTo(null);
        Proje3.KullanıcıŞarkı.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_şarkıButonActionPerformed

    private void profilButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilButonActionPerformed
        Proje3.profilID=Proje3.girilenKullanıcıID;
        Proje3.Profil = new Profil();
        Proje3.Profil.setLocationRelativeTo(null);
        Proje3.Profil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profilButonActionPerformed

    private void kullanıcıButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanıcıButonActionPerformed
        Proje3.Kullanıcılar = new Kullanıcılar();
        Proje3.Kullanıcılar.setLocationRelativeTo(null);
        Proje3.Kullanıcılar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kullanıcıButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullanıcıPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullanıcıPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullanıcıPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullanıcıPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullanıcıPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton albümButon;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton kullanıcıButon;
    private javax.swing.JButton profilButon;
    private javax.swing.JButton sanatçıButon;
    private javax.swing.JButton top10Buton;
    private javax.swing.JButton şarkıButon;
    // End of variables declaration//GEN-END:variables
}
