/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alperen
 */
public class KullanıcıŞarkı extends javax.swing.JFrame {

    /**
     * Creates new form KullanıcıŞarkı
     */
    public KullanıcıŞarkı() {
        initComponents();
        güncelle();
    }
    public void güncelle(){
        int i,j;
        try {
            Veritabanı.pstmt= Veritabanı.con.prepareStatement("SELECT sarkilar.sarki_id,sarkilar.sarki_ad,sanatcilar.sanatci_ad,albumler.album_ad,sarkilar.sarki_tarih,sarkilar.sarki_tur,sarkilar.sure,sarkilar.dinlenme FROM sarkilar JOIN sarkilar_sanatcilar ON (sarkilar.sarki_id=sarkilar_sanatcilar.sarki_id) JOIN sanatcilar ON (sanatcilar.sanatci_id=sarkilar_sanatcilar.sanatci_id)  JOIN sanatcilar_albumler ON (sanatcilar.sanatci_id=sanatcilar_albumler.sanatci_id) JOIN albumler ON (sanatcilar_albumler.album_id=albumler.album_id) WHERE (sarkilar.album_id=albumler.album_id)");
            Veritabanı.rs= Veritabanı.pstmt.executeQuery();
            ResultSetMetaData ŞarkıData = Veritabanı.rs.getMetaData();
            i = ŞarkıData.getColumnCount();
            DefaultTableModel RecordTable = (DefaultTableModel)şarkıTablo.getModel();
            RecordTable.setRowCount(0);
            while(Veritabanı.rs.next()){
                Vector columnData = new Vector();
                for(j=1;j<=i;j++){
                    columnData.add(Veritabanı.rs.getString("sarki_id"));
                    columnData.add(Veritabanı.rs.getString("sarki_ad"));
                    columnData.add(Veritabanı.rs.getString("sanatci_ad"));
                    columnData.add(Veritabanı.rs.getString("album_ad"));
                    columnData.add(Veritabanı.rs.getString("sarki_tarih"));
                    columnData.add(Veritabanı.rs.getString("sarki_tur"));
                    columnData.add(Veritabanı.rs.getString("sure"));
                    columnData.add(Veritabanı.rs.getString("dinlenme"));
                }
                RecordTable.addRow(columnData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(KullanıcıŞarkı.class.getName()).log(Level.SEVERE, null, ex);
        }
         
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        şarkıTablo = new javax.swing.JTable();
        geriDönButon = new javax.swing.JButton();
        ekleButon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtf_id = new javax.swing.JTextField();
        txtf_ad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        şarkıTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Şarkı Adı", "Sanatçı", "Albüm", "Tarih", "Tür", "Süre", "Dinlenme "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        şarkıTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                şarkıTabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(şarkıTablo);

        geriDönButon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        geriDönButon.setText("GERİ DÖN");
        geriDönButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriDönButonActionPerformed(evt);
            }
        });

        ekleButon.setText("EKLE");
        ekleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleButonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Şarkı ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Şarkı Adı");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtf_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ekleButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(geriDönButon, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtf_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addComponent(ekleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(geriDönButon, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geriDönButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriDönButonActionPerformed
        Proje3.KullanıcıPanel = new KullanıcıPanel();
        Proje3.KullanıcıPanel.setLocationRelativeTo(null);
        Proje3.KullanıcıPanel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_geriDönButonActionPerformed

    private void ekleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleButonActionPerformed
        
        try {
            Veritabanı.pstmt= Veritabanı.con.prepareStatement("INSERT INTO sarkilar_kullanicilar(sarki_id,kullanici_id) values (?,?)");
            Veritabanı.pstmt.setString(1, txtf_id.getText());
            Veritabanı.pstmt.setInt(2, Proje3.girilenKullanıcıID);
            Veritabanı.pstmt.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(KullanıcıŞarkı.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_ekleButonActionPerformed

    private void şarkıTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_şarkıTabloMouseClicked
        
        DefaultTableModel RecordTable = (DefaultTableModel) şarkıTablo.getModel();
        int seçilen = şarkıTablo.getSelectedRow();
        txtf_id.setText(RecordTable.getValueAt(seçilen, 0).toString());
        txtf_ad.setText(RecordTable.getValueAt(seçilen, 1).toString());
    }//GEN-LAST:event_şarkıTabloMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullanıcıŞarkı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullanıcıŞarkı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullanıcıŞarkı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullanıcıŞarkı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullanıcıŞarkı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ekleButon;
    private javax.swing.JButton geriDönButon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtf_ad;
    private javax.swing.JTextField txtf_id;
    private javax.swing.JTable şarkıTablo;
    // End of variables declaration//GEN-END:variables
}
