
package main;

import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Sanatçılar extends javax.swing.JFrame {

    /**
     * Creates new form Sanatçılar
     */
    public Sanatçılar() {
        initComponents();
        güncelle();
    }

    
    public void güncelle(){
        int i,j;
        try {
            Veritabanı.pstmt= Veritabanı.con.prepareStatement("SELECT * FROM sanatcilar");
            Veritabanı.rs= Veritabanı.pstmt.executeQuery();
            ResultSetMetaData AlbumData = Veritabanı.rs.getMetaData();
            i = AlbumData.getColumnCount();
            DefaultTableModel RecordTable = (DefaultTableModel)sanatçıTablo.getModel();
            RecordTable.setRowCount(0);
            while(Veritabanı.rs.next()){
                Vector columnData = new Vector();
                for(j=1;j<=i;j++){
                    columnData.add(Veritabanı.rs.getString("sanatci_id"));
                    columnData.add(Veritabanı.rs.getString("sanatci_ad"));
                    columnData.add(Veritabanı.rs.getString("sanatci_ulke"));
                }
                RecordTable.addRow(columnData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Sanatçılar.class.getName()).log(Level.SEVERE, null, ex);
        }
            
         
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        sanatçıTablo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtf_ad = new javax.swing.JTextField();
        txtf_ülke = new javax.swing.JTextField();
        ekleButon = new javax.swing.JButton();
        silButon = new javax.swing.JButton();
        güncelleButon = new javax.swing.JButton();
        bitirButon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sanatçıTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Adı", "Ülkesi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sanatçıTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sanatçıTabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sanatçıTablo);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Adı");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Ülkesi");

        ekleButon.setText("EKLE");
        ekleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleButonActionPerformed(evt);
            }
        });

        silButon.setText("SİL");
        silButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silButonActionPerformed(evt);
            }
        });

        güncelleButon.setText("GÜNCELLE");
        güncelleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                güncelleButonActionPerformed(evt);
            }
        });

        bitirButon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bitirButon.setText("BİTİR");
        bitirButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bitirButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtf_ad, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addComponent(txtf_ülke)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ekleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(güncelleButon)
                                    .addComponent(silButon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 247, Short.MAX_VALUE)
                        .addComponent(bitirButon, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtf_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtf_ülke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(ekleButon)
                .addGap(51, 51, 51)
                .addComponent(silButon)
                .addGap(49, 49, 49)
                .addComponent(güncelleButon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(bitirButon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sanatçıTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sanatçıTabloMouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel) sanatçıTablo.getModel();
        int seçilen = sanatçıTablo.getSelectedRow();
        txtf_ad.setText(RecordTable.getValueAt(seçilen, 1).toString());
        txtf_ülke.setText(RecordTable.getValueAt(seçilen, 2).toString());
       
    }//GEN-LAST:event_sanatçıTabloMouseClicked

    private void ekleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleButonActionPerformed
        try {
            Veritabanı.pstmt= Veritabanı.con.prepareStatement("INSERT INTO sanatcilar(sanatci_ad,sanatci_ulke) values (?,?)");
            Veritabanı.pstmt.setString(1, txtf_ad.getText());
            Veritabanı.pstmt.setString(2, txtf_ülke.getText());
            Veritabanı.pstmt.executeUpdate();
            güncelle();
        } catch (SQLException ex) {
            Logger.getLogger(Sanatçılar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ekleButonActionPerformed

    private void silButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silButonActionPerformed
        
        DefaultTableModel RecordTable = (DefaultTableModel) sanatçıTablo.getModel();
        int seçilen = sanatçıTablo.getSelectedRow();
        try {
        int id = Integer.parseInt(RecordTable.getValueAt(seçilen, 0).toString());
        int veriyiSil = JOptionPane.showConfirmDialog(null,"Silmek istediğinizden emin misiniz?","Uyarı",JOptionPane.YES_NO_OPTION);
        if(veriyiSil== JOptionPane.YES_OPTION){
            
                Veritabanı.pstmt = Veritabanı.con.prepareStatement("DELETE FROM sanatcilar WHERE sanatci_id=?");
                Veritabanı.pstmt.setInt(1, id);
                Veritabanı.pstmt.executeUpdate();
                güncelle();
                txtf_ad.setText("");
                txtf_ülke.setText("");  
            } 
            }catch (SQLException ex) {
                Logger.getLogger(Sanatçılar.class.getName()).log(Level.SEVERE, null, ex);
            } 
        
    }//GEN-LAST:event_silButonActionPerformed

    private void güncelleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_güncelleButonActionPerformed
        
        
            DefaultTableModel RecordTable = (DefaultTableModel) sanatçıTablo.getModel();
            int seçilen = sanatçıTablo.getSelectedRow();
            try {
            int id = Integer.parseInt(RecordTable.getValueAt(seçilen, 0).toString());
            Veritabanı.pstmt= Veritabanı.con.prepareStatement("UPDATE sanatcilar set sanatci_ad=?,sanatci_ulke=? WHERE sanatci_id=?");
            Veritabanı.pstmt.setString(1, txtf_ad.getText());
            Veritabanı.pstmt.setString(2, txtf_ülke.getText());
            Veritabanı.pstmt.setInt(3, id);
            Veritabanı.pstmt.executeUpdate();
            güncelle();
        } catch (SQLException ex) {
            Logger.getLogger(Sanatçılar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_güncelleButonActionPerformed

    private void bitirButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bitirButonActionPerformed
        Proje3.AdminPanel= new AdminPanel();
        Proje3.AdminPanel.setLocationRelativeTo(null);
        Proje3.AdminPanel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bitirButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sanatçılar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sanatçılar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sanatçılar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sanatçılar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sanatçılar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bitirButon;
    private javax.swing.JButton ekleButon;
    private javax.swing.JButton güncelleButon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable sanatçıTablo;
    private javax.swing.JButton silButon;
    private javax.swing.JTextField txtf_ad;
    private javax.swing.JTextField txtf_ülke;
    // End of variables declaration//GEN-END:variables
}
