package main;

import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Şarkılar extends javax.swing.JFrame {

    /**
     * Creates new form Şarkılar
     */
    public Şarkılar() {
        initComponents();
        güncelle();
    }
    
    
    
    public void güncelle(){
        int i,j;
        try {
            Veritabanı.pstmt= Veritabanı.con.prepareStatement("SELECT * FROM sarkilar");
            Veritabanı.rs= Veritabanı.pstmt.executeQuery();
            ResultSetMetaData ŞarkıData = Veritabanı.rs.getMetaData();
            i = ŞarkıData.getColumnCount();
            DefaultTableModel RecordTable = (DefaultTableModel)şarkıTablo.getModel();
            RecordTable.setRowCount(0);
            while(Veritabanı.rs.next()){
                Vector columnData = new Vector();
                for(j=1;j<=i;j++){
                    columnData.add(Veritabanı.rs.getString("sarki_id"));
                    columnData.add(Veritabanı.rs.getString("sarki_ad"));
                    columnData.add(Veritabanı.rs.getString("sarki_tarih"));
                    columnData.add(Veritabanı.rs.getString("sarki_tur"));
                    columnData.add(Veritabanı.rs.getString("sure"));
                    columnData.add(Veritabanı.rs.getString("dinlenme"));
                    columnData.add(Veritabanı.rs.getString("album_id"));
                }
                RecordTable.addRow(columnData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Şarkılar.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        şarkıTablo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtf_ad = new javax.swing.JTextField();
        txtf_tarih = new javax.swing.JTextField();
        txtf_tür = new javax.swing.JTextField();
        txtf_süre = new javax.swing.JTextField();
        txtf_dinlenme = new javax.swing.JTextField();
        txtf_albümid = new javax.swing.JTextField();
        ekleButon = new javax.swing.JButton();
        silButon = new javax.swing.JButton();
        güncelleButon = new javax.swing.JButton();
        bitirButon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        şarkıTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Adı", "Çıkış Tarihi", "Türü", "Süresi", "Dinlenme Sayısı", "Albüm ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        şarkıTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                şarkıTabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(şarkıTablo);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Şarkı Adı");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Çıkış Tarihi");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Türü");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Süresi");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Dinlenme");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Albüm ID");

        ekleButon.setText("EKLE");
        ekleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleButonActionPerformed(evt);
            }
        });

        silButon.setText("SİL");
        silButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silButonActionPerformed(evt);
            }
        });

        güncelleButon.setText("GÜNCELLE");
        güncelleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                güncelleButonActionPerformed(evt);
            }
        });

        bitirButon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bitirButon.setText("BİTİR");
        bitirButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bitirButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtf_dinlenme)
                            .addComponent(txtf_süre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtf_tür, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtf_tarih, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtf_ad, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtf_albümid, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(silButon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ekleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(güncelleButon)
                            .addComponent(bitirButon, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtf_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtf_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtf_tür, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtf_süre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtf_dinlenme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtf_albümid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(ekleButon)
                        .addGap(32, 32, 32)
                        .addComponent(silButon)
                        .addGap(26, 26, 26)
                        .addComponent(güncelleButon)
                        .addGap(43, 43, 43)
                        .addComponent(bitirButon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void şarkıTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_şarkıTabloMouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel) şarkıTablo.getModel();
        int seçilen = şarkıTablo.getSelectedRow();
        txtf_ad.setText(RecordTable.getValueAt(seçilen, 1).toString());
        txtf_tarih.setText(RecordTable.getValueAt(seçilen, 2).toString());
        txtf_tür.setText(RecordTable.getValueAt(seçilen, 3).toString());
        txtf_süre.setText(RecordTable.getValueAt(seçilen, 4).toString());
        txtf_dinlenme.setText(RecordTable.getValueAt(seçilen, 5).toString());
        txtf_albümid.setText(RecordTable.getValueAt(seçilen, 6).toString());
    }//GEN-LAST:event_şarkıTabloMouseClicked

    private void ekleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleButonActionPerformed
        
        try {
            Veritabanı.pstmt= Veritabanı.con.prepareStatement("INSERT INTO sarkilar(sarki_ad,sarki_tarih,sarki_tur,sure,dinlenme,album_id) values (?,?,?,?,?,?)");
            Veritabanı.pstmt.setString(1, txtf_ad.getText());
            Veritabanı.pstmt.setString(2, txtf_tarih.getText());
            Veritabanı.pstmt.setString(3, txtf_tür.getText());
            Veritabanı.pstmt.setString(4, txtf_süre.getText());
            Veritabanı.pstmt.setString(5, txtf_dinlenme.getText());
            Veritabanı.pstmt.setString(6, txtf_albümid.getText());
            Veritabanı.pstmt.executeUpdate();
            güncelle();
        } catch (SQLException ex) {
            Logger.getLogger(Şarkılar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_ekleButonActionPerformed

    private void silButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silButonActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel) şarkıTablo.getModel();
        int seçilen = şarkıTablo.getSelectedRow();
        try {
        int id = Integer.parseInt(RecordTable.getValueAt(seçilen, 0).toString());
        int veriyiSil = JOptionPane.showConfirmDialog(null,"Silmek istediğinizden emin misiniz?","Uyarı",JOptionPane.YES_NO_OPTION);
        if(veriyiSil== JOptionPane.YES_OPTION){
                Veritabanı.pstmt = Veritabanı.con.prepareStatement("DELETE FROM sarkilar WHERE sarki_id=?");
                Veritabanı.pstmt.setInt(1, id);
                Veritabanı.pstmt.executeUpdate();
                güncelle();
                txtf_ad.setText("");
                txtf_tarih.setText("");
                txtf_tür.setText("");
                txtf_süre.setText("");
                txtf_dinlenme.setText("");
                txtf_albümid.setText("");
            } 
            }catch (SQLException ex) {
                Logger.getLogger(Şarkılar.class.getName()).log(Level.SEVERE, null, ex);
            } 
        
        
    }//GEN-LAST:event_silButonActionPerformed

    private void güncelleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_güncelleButonActionPerformed
        
            DefaultTableModel RecordTable = (DefaultTableModel) şarkıTablo.getModel();
            int seçilen = şarkıTablo.getSelectedRow();
            try {
            int id = Integer.parseInt(RecordTable.getValueAt(seçilen, 0).toString());
            Veritabanı.pstmt= Veritabanı.con.prepareStatement("UPDATE sarkilar set sarki_ad=?,sarki_tarih=?,sarki_tur=?, sure=?,dinlenme=?,album_id=? WHERE sarki_id=?");
            Veritabanı.pstmt.setString(1, txtf_ad.getText());
            Veritabanı.pstmt.setString(2, txtf_tarih.getText());
            Veritabanı.pstmt.setString(3, txtf_tür.getText());
            Veritabanı.pstmt.setString(4, txtf_süre.getText());
            Veritabanı.pstmt.setString(5, txtf_dinlenme.getText());
            Veritabanı.pstmt.setString(6, txtf_albümid.getText());
            Veritabanı.pstmt.setInt(7, id);
            Veritabanı.pstmt.executeUpdate();
            güncelle();
        } catch (SQLException ex) {
            Logger.getLogger(Şarkılar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_güncelleButonActionPerformed

    private void bitirButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bitirButonActionPerformed
        Proje3.AdminPanel= new AdminPanel();
        Proje3.AdminPanel.setLocationRelativeTo(null);
        Proje3.AdminPanel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bitirButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Şarkılar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Şarkılar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Şarkılar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Şarkılar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Şarkılar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bitirButon;
    private javax.swing.JButton ekleButon;
    private javax.swing.JButton güncelleButon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton silButon;
    private javax.swing.JTextField txtf_ad;
    private javax.swing.JTextField txtf_albümid;
    private javax.swing.JTextField txtf_dinlenme;
    private javax.swing.JTextField txtf_süre;
    private javax.swing.JTextField txtf_tarih;
    private javax.swing.JTextField txtf_tür;
    private javax.swing.JTable şarkıTablo;
    // End of variables declaration//GEN-END:variables
}
